<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RobloxAccountManagerPro.Core</AssemblyName>
    <RootNamespace>RobloxAccountManagerPro.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.Process" Version="4.3.0" />
  </ItemGroup>

</Project>
